INFO:root:Reading edge lists...
INFO:root:...just read 1000 edge list
INFO:root:Defining an InfluenceMaximization problem...
Traceback (most recent call last):
  File "TestModule.py", line 79, in <module>
    newProblem = InfluenceMaximization(graphs, args.constraints)
  File "/scratch/ozcan.g/WDNFFunctions/ProblemInstances.py", line 341, in __init__
    P[node1] = tuple(sorted([node1] + list(paths.predecessors(node1))))
  File "/shared/centos7/python/2.7.15/lib/python2.7/site-packages/networkx/classes/digraph.py", line 793, in predecessors
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node 263 is not in the digraph.
srun: error: c3124: task 0: Exited with exit code 1
